on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Testing'
        run: pwd

      - name: 'Tes'
        run: echo hello

      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Listing'
        run: ls -a

      - name: 'Login to Docker'
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: 'Build image'
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/yara_ahmed_2023040277 .

      - name: 'Push image'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/yara_ahmed_2023040277