on:
  push:
    branches:
      - master 






jobs:
   build:
      runs-on: ubuntu-latest
      
         
      steps:
         - name: 'Testing'
           run: pwd

         - name: 'Test'
           run: echo hello 

         - uses: actions/checkout@v3

         - name: 'listing'
           run: ls -a

         - name: 'Login to Docker'
           run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}
         - name: 'build image'
           run: docker build -t ${{secrets.DOCKER_USERNAME}}/yara_ahmed_2023040277 .

         - name: 'push image'
           run: docker push ${{secrets.DOCKER_USERNAME}}/yara_ahmed_2023040277