name: Build and Push Docker Image
on:
  push:
    branches: 
        - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Check repository'
        uses: actions/checkout@v3



      - name: 'Test'
        run: echo hello

      - name: 'Listing'
        run: ls -a


      - name: 'Login to Docker'
        run:  docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: 'Build image'
        run:  docker build -t ${{ secrets.DOCKER_USERNAME }}/yara_ahmed2023040277 .


      - name: 'Push Docker image'
        run:  docker push ${{ secrets.DOCKER_USERNAME }}/yara_ahmed2023040277


          
